"""
Interview Management Agents of this website
"""

from typing import Optional

from app.ai.provider import get_provider


# ============================================================
# Interview Manager Agent
# ============================================================

class InterviewManagerAgent:
    """For this site responsblity to track your questions
    """

    def __init__(self, max_questions: int = 8):
        self.provider = get_provider()
        self.max_questions = max(1, max_questions)

    # -----------------------
    # Difficulty adaptation
    # ------------------------
    def _adapt_difficulty(
        self,
        difficulty: str,
        last_score: Optional[float],
    ) -> str:
        """
        The interview difficulty adaptation logic.

        Score >= 85:
            Increase difficulty.

        Score < 55:
            Decrease difficulty.

        Otherwise:
            Keep the same difficulty.
        """

        difficulties = [
            "Beginner",
            "Intermediate",
            "Advanced",
            "Expert",
        ]

        normalized_difficulty = (
            difficulty.strip().title()
            if difficulty
            else "Intermediate"
        )

        if normalized_difficulty not in difficulties:
            normalized_difficulty = "Intermediate"

        if last_score is None:
            return normalized_difficulty

        try:
            score = float(last_score)
        except (TypeError, ValueError):
            return normalized_difficulty

        current_index = difficulties.index(normalized_difficulty)

        if score >= 85:
            current_index = min(
                current_index + 1,
                len(difficulties) - 1,
            )

        elif score < 55:
            current_index = max(
                current_index - 1,
                0,
            )

        return difficulties[current_index]

    # --------------------------------------------------------
    # Next question
    # --------------------------------------------------------

    def get_next_question(
        self,
        interview_type: str,
        role: str,
        difficulty: str,
        asked_topics: list[str],
        last_score: Optional[float] = None,
        question_number: int = 1,
    ) -> dict:
        """
        The questions are generated by the AI provider based on the
        interview type, role, difficulty, and previously asked topics.
        Parameters:
        interview_type: The type of interview (e.g., "technical", "behavioral").
        role: The role for which the interview is being conducted (e.g., "Software Engineer
        """

        # Safety normalization
        question_number = max(1, int(question_number or 1))

        # Make sure asked_topics is always a list
        if not isinstance(asked_topics, list):
            asked_topics = []

        # Adapt difficulty
        adapted_difficulty = self._adapt_difficulty(
            difficulty=difficulty,
            last_score=last_score,
        )

        # Ask the AI provider for a question
        question = self.provider.get_question(
            interview_type=interview_type,
            role=role,
            difficulty=adapted_difficulty,
            asked_topics=asked_topics,
        )

        # Make sure provider returned a dictionary
        if not isinstance(question, dict):
            question = {
                "question": str(question),
            }

        # Interview completion
        is_last = question_number >= self.max_questions

        return {
            **question,
            "adapted_difficulty": adapted_difficulty,
            "question_number": question_number,
            "total_questions": self.max_questions,
            "is_last": is_last,
        }

    # --------------------------------------------------------
    # Check interview completion
    # --------------------------------------------------------

    def is_interview_complete(
        self,
        question_number: int,
    ) -> bool:
        """
        Return True when the maximum number of questions
        has been reached.
        """

        return int(question_number or 0) >= self.max_questions


# =====================
# Evaluation Agent
# =====================

class EvaluationAgent:
    """
    Evaluates candidate answers using the configured AI provider.
    """

    def __init__(self):
        self.provider = get_provider()

    # -------------------
    # Evaluate answer
    # -------------------

    def evaluate_answer(
        self,
        question: str,
        answer: str,
        question_type: str = "technical",
    ) -> dict:
        """
        Evaluate a single interview answer.

        The actual evaluation is delegated to the AI provider.
        """

        if not question:
            raise ValueError("Question cannot be empty.")

        if not answer or not answer.strip():
            return {
                "score": 0,
                "feedback": "No answer was provided.",
                "strengths": [],
                "improvements": [
                    "Provide a clear answer to the question."
                ],
            }

        result = self.provider.evaluate_answer(
            question,
            answer,
        )

        if isinstance(result, dict):
            return result

        return {
            "score": 0,
            "feedback": str(result),
        }

    # --------------------------------------------------------
    # Final report
    # --------------------------------------------------------

    def generate_final_report(
        self,
        answers: list[dict],
        config: dict,
    ) -> dict:
        """
        Generate the final interview report.

        The AI provider generates the main scores.
        Communication metrics are calculated from actual
        available answer data when possible.
        """

        if not isinstance(answers, list):
            answers = []

        if not isinstance(config, dict):
            config = {}

        # Generate AI-based final scores
        scores = self.provider.generate_final_scores(
            answers
        )

        if not isinstance(scores, dict):
            scores = {}

        # ----------------------------------------------------
        # Collect answer-level information
        # ----------------------------------------------------

        numeric_scores = []

        for item in answers:
            if not isinstance(item, dict):
                continue

            score = item.get("score")

            if score is None:
                score = item.get("overall_score")

            try:
                if score is not None:
                    numeric_scores.append(float(score))
            except (TypeError, ValueError):
                continue

        # ----------------------------------------------------
        # Calculate basic performance information
        # ----------------------------------------------------

        average_score = None

        if numeric_scores:
            average_score = round(
                sum(numeric_scores) / len(numeric_scores),
                2,
            )

        # ----------------------------------------------------
        # Build dynamic strengths/improvements
        # ----------------------------------------------------

        strengths = []
        improvements = []

        if average_score is not None:

            if average_score >= 85:
                strengths.append(
                    "Strong overall interview performance."
                )

            elif average_score >= 70:
                strengths.append(
                    "Good understanding of the interview topics."
                )

            else:
                improvements.append(
                    "Strengthen understanding of core concepts."
                )

        # Extract provider-generated feedback if available
        for item in answers:

            if not isinstance(item, dict):
                continue

            item_strengths = item.get("strengths", [])

            if isinstance(item_strengths, list):
                for strength in item_strengths:
                    if (
                        strength
                        and strength not in strengths
                    ):
                        strengths.append(strength)

            item_improvements = item.get(
                "improvements",
                [],
            )

            if isinstance(item_improvements, list):
                for improvement in item_improvements:
                    if (
                        improvement
                        and improvement not in improvements
                    ):
                        improvements.append(
                            str(improvement)
                        )

        # Fallbacks
        if not strengths:
            strengths = [
                "Clear attempt to answer the interview questions.",
                "Demonstrated problem-solving approach.",
            ]

        if not improvements:
            improvements = [
                "Provide more specific examples.",
                "Keep answers structured and concise.",
            ]

        recommendations = [
            "Practice interview questions regularly.",
            "Use the STAR framework for behavioral questions.",
            "Strengthen weak technical areas identified in the report.",
            "Practice explaining projects with clear technical details.",
        ]

        # ----------------------------------------------------
        # Return final report
        # ----------------------------------------------------

        report = {
            **scores,
            "strengths": strengths[:5],
            "improvements": improvements[:5],
            "recommendations": recommendations,
            "questions_attempted": len(answers),
        }

        if average_score is not None:
            report["average_answer_score"] = average_score

        # Do NOT use fake hard-coded communication metrics.
        # - speech-to-text transcript
        # Until that pipeline is connected, return an explicit
        # unavailable state instead of fake numbers.

        report["communication_metrics"] = {
            "speaking_speed": None,
            "filler_words": None,
            "avg_pause": None,
            "clarity": None,
            "vocabulary": None,
            "answer_structure": None,
            "status": "not_available",
        }

        # Same approach for STAR scoring.
        # It should eventually come from AI analysis of
        # behavioral answers rather than hard-coded numbers.

        report["star_scores"] = {
            "overall": None,
            "situation": None,
            "task": None,
            "action": None,
            "result": None,
            "status": "not_available",
        }

        return report


# ================
# Resume Agent
# ================

class ResumeAgent:
    """
    Analyzes candidate resumes.
    """

    def __init__(self):
        self.provider = get_provider()

    def analyze(
        self,
        resume_text: str,
        user_skills: Optional[list[str]] = None,
    ) -> dict:
        """
        Analyze resume content using the AI provider.
        """

        if not resume_text or not resume_text.strip():
            return {
                "score": 0,
                "feedback": "Resume text is empty.",
            }

        result = self.provider.analyze_resume(
            resume_text
        )

        if isinstance(result, dict):
            return result

        return {
            "feedback": str(result),
        }


# =============
# Job Agent
# =============

class JobAgent:
    """
    Analyzes job descriptions against candidate skills.
    """

    def __init__(self):
        self.provider = get_provider()

    def analyze(
        self,
        job_description: str,
        user_skills: list[str],
    ) -> dict:
        """
        Analyze a job description and compare it with
        candidate skills.
        """

        if not job_description or not job_description.strip():
            return {
                "score": 0,
                "feedback": "Job description is empty.",
            }

        if not isinstance(user_skills, list):
            user_skills = []

        result = self.provider.analyze_job(
            job_description,
            user_skills,
        )

        if isinstance(result, dict):
            return result

        return {
            "feedback": str(result),
        }


# ==========================
# Career Coach Agent
# ==========================

class CareerCoachAgent:
    """
    Generates a career development roadmap.

    This currently uses a structured roadmap.
    It can later be connected to the AI provider so that
    recommendations are generated from actual interview
    performance.
    """

    def generate_roadmap(
        self,
        role: str,
        skills: list[str],
        interview_scores: list[dict],
    ) -> dict:
        """
        Generate a structured career roadmap.
        """

        if not isinstance(skills, list):
            skills = []

        if not isinstance(interview_scores, list):
            interview_scores = []

        # ----------------------------------------------------
        # Identify weak areas from interview scores
        # ----------------------------------------------------

        weak_areas = [
            "System Design",
            "Cloud Technologies",
            "MLOps",
        ]

        return {
            "target_role": role,
            "current_readiness": self._calculate_readiness(
                interview_scores
            ),
            "week_plan": [
                {
                    "week": 1,
                    "title": "Python + DSA Foundations",
                    "tasks": [
                        "Complete 30 LeetCode medium problems",
                        "Review advanced Python concepts",
                        "Practice 5 interview questions daily",
                    ],
                },
                {
                    "week": 2,
                    "title": "Machine Learning Deep Dive",
                    "tasks": [
                        "Review core ML algorithms",
                        "Practice ML system design",
                        "Complete 2 ML mini projects",
                    ],
                },
                {
                    "week": 3,
                    "title": "Deep Learning + Generative AI",
                    "tasks": [
                        "Study transformer architecture",
                        "Build a RAG application",
                        "Practice Generative AI interview questions",
                    ],
                },
                {
                    "week": 4,
                    "title": "Mock Interviews + Projects",
                    "tasks": [
                        "Complete 5 full mock interviews",
                        "Polish resume and GitHub",
                        "Practice 5 system design problems",
                    ],
                },
            ],
            "weak_areas": weak_areas,
        }

    # --------------------------------------------------------
    # Readiness calculation
    # --------------------------------------------------------

    def _calculate_readiness(
        self,
        interview_scores: list[dict],
    ) -> int:
        """
        Calculate basic readiness from available interview
        scores instead of always returning a fixed value.
        """

        scores = []

        for item in interview_scores:

            if not isinstance(item, dict):
                continue

            score = item.get("score")

            if score is None:
                score = item.get("overall_score")

            try:
                if score is not None:
                    scores.append(float(score))
            except (TypeError, ValueError):
                continue

        if not scores:
            return 0

        readiness = sum(scores) / len(scores)

        return max(
            0,
            min(
                100,
                round(readiness),
            ),
        )